### ISSUE TITLE
エンカウントテーブルを数値ではなく名前で選択したい

### ISSUE THREAD

**Issue by pingval** [Maru0137/dqrta-info#3]
エンカウントテーブルをEncount table idで選ぶところ、リストボックスを使うなどして名前で選択できるようにしてほしいです。

今は [PS2版DQ5エンカウントテーブル表.xlsx](http://ux.getuploader.com/Maru0137/download/10/PS2DQ5_enc.zip) とにらめっこして入力してます……。

**Comment by Maru0137** [comment]
@pingval セレクトボックスで選択 & エリア名を表示するようにしてみました。 (637bcc01b94bd3edc5da4236ebc18518123aa374)エリア名は[エンカウントテーブル](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vSbXmZy0r33V16-iJTJk3sTnP8wSPqiUcIScll6kcJPdQN7JdadZO6XEknfS4TEZ_OltVTwVaCap_OC/pubhtml?gid=0&single=true)に記載しているものと合わせています。

UI的にはいかがでしょう？

**Comment by pingval** [comment]
自分にとってはかなりよい感じです。ありがとうございます。
